[package]
name = "labelbatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genpdf = "0.2.0"
font-kit = "0.11.0"
serde = { version = "1.0.143", features = ["derive"] }
anyhow = "1.0.61"
